baseURL: http://www.shiftsecurityleft.io
languageCode: en-us
title: Shift Security Left
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/SSL-Logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Enterprise Security. Start-Up Agility.  
    # Hero subtitle (optional)
    subtitle: Shift security left to unleash developer agility with best practices built in.
    # Button text
    buttontext: Learn More
    # Where the main hero button links to
    buttonlink: "/shiftsecurityleft"
    # Hero image (from static/images/___)
    image: illustrations/SSL-Final-Big.png
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    #- systek
    #- tribe
    #- kromo
    #- infinite
    #- gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /
  - title: Infrapipe
    url: /infrapipe
    sublinks:
      - title: Overview
        url: /infrapipe
      - title: Docs
        url: https://infrapipe.shiftsecurityleft.io/docs
      - title: Github Repo
        url: https://github.com/shiftsecurityleft/example-nodejs-express-app
  - title: About Us
    sublinks:
      - title: Who are we
        url: /aboutus
      - title: What is Shift Security Left
        url: /shiftsecurityleft
      - title: SASSE
        url: /sasse
  - title: Contact Us
    url: /contactus
  #- title: Sign up
  #  url: /
  #  button: true
  section1:
    title: Learn more about what we got going on
    subtitle: and why it works for start-ups, small/medium businesses and enterprises.
    tiles:
    - title: Shift Security Left
      icon: previous
      text: What does Shifting Security Left mean?
      url: /shiftsecurityleft
      buttonText: Learn More
    - title: Products
      icon: products
      text: Learn more about products we are working on
      url: /products
      buttonText: Learn More
    - title: What's Coming
      icon: direction
      text: What is coming on our roadmap
      url: /whatscoming
      buttonText: Get started
  section2:
    title: Why our solutions are different
    subtitle: And how can you benefit
    features:
    - title: SIMPLE
      text: Single holistic end-to-end full-stack solutions to confidently deliver assets, code and infrastructure.
      # Icon (from /images/illustrations/icons/___.svg)
      #icon: 
    - title: AUTOMATED
      text: Codifying everything with smart integrations and leveraging automation to increase repeatability, consistency, simplicity.
      #icon: 
    - title: SECURE
      text: Deploying with known good, battle tested patterns with continuous validation from the start means making risk, audit and governance teams happy you are meeting their controls from initial push to dev.
      #icon: 
    - title: SUSTAINABLE
      text: Solutions that scale and won't increase your IT, DevOps, SRE workforce when the number of applications increase or the frequency of deployment increases.
      #icon: 
    - title: EVIDENCED
      text: Solutions that collect evidence at DevOps speed to have the information to back up what you say you are doing when you need to prove it.
      #icon: 
  #section3:
  #  title: One platform
  #  subtitle: To rule them all
  #  image: illustrations/mockups/app-mockup.png
  #  buttonText: Get started
  #  buttonLink: "#"
  section4: false
  #  title: Our Clients love us!
  #  subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #  clients:
  #  - name: Irma Walters
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Accountant
  #    img: 1
  #  - name: John Bradley
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: Financial Analyst
  #    img: 2
  #  - name: Gary Blackman
  #    quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #    job: HR Manager
  #    img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: SSL-Logo-No-Text.png
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/shiftsecurityleft
      # Icons are from Font Awesome
      icon: github
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/shiftsecleft
      icon: twitter
    bulmalogo: false
    quicklinks:
      column1:
        title: "Learn More"
        links:
        - text: About Us
          link: /aboutus
        - text: Shift Security Left
          link: /shiftsecurityleft
        - text: What's Coming
          link: /whatscoming
      column2:
        title: "Docs"
        links:
        - text: Infrapipe
          link: https://infrapipe.readme.io/docs
        - text: Infrapipe Quick Start Guide
          link: https://infrapipe.readme.io/docs/getting-started
        - text: Infrapipe Architecture 
          link: https://infrapipe.shiftsecurityleft.io/docs/deployment-architecture
      column3:
        title: "Links"
        links:
        - text: Credits
          link: /credits
